---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: This is the first version of API
components:
  schemas:
    district_with_polygon:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - polygon
      - polygon_type
      - center_coord
      - automatic_post_office_stats
    district:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - automatic_post_office_stats
    area_with_polygon:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
        emblem_url:
          type: string
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
      - polygon
      - polygon_type
      - center_coord
      - automatic_post_office_stats
    area:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        emblem_url:
          type: string
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
      - automatic_post_office_stats
    placement_object_type:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
      - id
      - name
    automatic_post_office:
      type: object
      properties:
        id:
          type: integer
        geo_data:
          type: array
          items:
            type: number
        area_id:
          type: integer
        is_placed:
          type: boolean
        address:
          type: string
        placement_object_type_id:
          type: integer
        people_in_range:
          type: integer
        distance_to_metro:
          type: integer
        distance_to_bus:
          type: integer
        predict_a:
          type: number
        predict_b:
          type: number
        predict_c:
          type: number
      required:
      - geo_data
      - area_id
      - is_placed
      - address
      - placement_object_type_id
      - people_in_range
      - distance_to_metro
      - distance_to_bus
      - predict_a
      - predict_b
      - predict_c
    meta:
      type: object
      properties:
        current_page:
          type: integer
        next_page:
          oneOf:
          - type: integer
          - type: 'null'
        prev_page:
          oneOf:
          - type: integer
          - type: 'null'
        total_pages:
          type: integer
        total_count:
          type: integer
      required:
      - current_page
      - next_page
      - prev_page
      - total_pages
      - total_count
    automatic_post_office_stats:
      type: object
      properties:
        placed:
          type: integer
        not_placed:
          type: integer
      required:
      - placed
      - not_placed
    automatic_post_office_with_meta:
      type: object
      properties:
        automatic_post_offices:
          type: array
          items:
            "$ref": "#/components/schemas/automatic_post_office"
        meta:
          "$ref": "#/components/schemas/meta"
      required:
      - automatic_post_offices
paths:
  "/areas/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: number
    get:
      summary: Show area by id
      tags:
      - Areas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 507
                    population: 240014
                    square: 85290.16
                    name: Сосновая пл.
                    population_density: 83.62
                    square_housing_stock: 81.49
                    living_square_per_person: 43.72
                    district_id: 522
                    2gis_id: 9838922285
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnNCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6e13a8ac21bbf3a5527fc71e1848f8fb7b50e355/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                    polygon:
                    - - - 27336.590837
                        - 51054.173253
                      - - 31317.881854
                        - 44153.541166
                    polygon_type: 1
                    center_coord:
                    - 82013.380588
                    - 82265.087724
              schema:
                "$ref": "#/components/schemas/area_with_polygon"
        '404':
          description: Not found
  "/districts/{district_id}/areas":
    parameters:
    - name: district_id
      in: path
      description: District id
      required: true
      schema:
        type: number
    get:
      summary: Array areas by district
      tags:
      - Areas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 510
                    population: 649678
                    square: 31988.27
                    name: Молодежная проспект
                    population_density: 89.85
                    square_housing_stock: 91.66
                    living_square_per_person: 34.25
                    district_id: 525
                    2gis_id: 3858235144
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjRCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1e5fdb85c9d8b1805688945941d0b7ab1bc458be/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                  - id: 511
                    population: 554031
                    square: 58747.16
                    name: Сосновая ул.
                    population_density: 88.39
                    square_housing_stock: 57.33
                    living_square_per_person: 88.11
                    district_id: 525
                    2gis_id: 4877239928
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjhCIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1546d24abffc1d73ce3de9b5f7ef30fc72b6140b/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/area"
  "/automatic_post_offices/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: number
    get:
      summary: Show automatic post office by id
      tags:
      - Automatic post offices
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 447
                    geo_data:
                    - 16343.510113
                    - 91033.052807
                    area_id: 512
                    is_placed: true
                    address: 959883 Россия, Уфа, пр. Вокзальная, 590
                    placement_object_type_id: 462
                    people_in_range: 93215
                    distance_to_metro: 523
                    distance_to_bus: 194
                    predict_a: 35915.483
                    predict_b: 68450.318
                    predict_c: 56991.305
              schema:
                "$ref": "#/components/schemas/automatic_post_office"
        '404':
          description: Not found
  "/automatic_post_offices/export_xlsx":
    get:
      summary: Export xlsx file with automatic post offices data
      tags:
      - Automatic post offices
      parameters:
      - name: area_id
        in: query
        description: Filter by area id
        required: false
        schema:
          type: number
      - name: district_id
        in: query
        description: Filter by district id
        required: false
        schema:
          type: number
      - name: placement_object_type_id
        in: query
        description: Filter by placement object type id
        required: false
        schema:
          type: number
      - name: is_placed
        in: query
        description: Automatic post office is placed?
        required: false
        schema:
          type: boolean
      - name: sort
        in: query
        description: 'Sorting by object fields. Before field: ''+'' or nothing ->
          ASC, ''-'' -> DESC'
        required: false
        example: "-distance_to_metro,distance_to_bus,+predict_a"
        schema:
          type: string
      responses:
        '404':
          description: Not found
        '200':
          description: Successful
  "/automatic_post_offices":
    get:
      summary: Array automatic post offices with pagination
      tags:
      - Automatic post offices
      parameters:
      - name: page
        in: query
        description: Page number
        required: false
        example: 1
        schema:
          type: number
      - name: per_page
        in: query
        description: Number of elements per page
        required: false
        example: 1
        schema:
          type: number
      - name: area_id
        in: query
        description: Filter by area id
        required: false
        schema:
          type: number
      - name: district_id
        in: query
        description: Filter by district id
        required: false
        schema:
          type: number
      - name: placement_object_type_id
        in: query
        description: Filter by placement object type id
        required: false
        schema:
          type: number
      - name: is_placed
        in: query
        description: Automatic post office is placed?
        required: false
        schema:
          type: boolean
      - name: sort
        in: query
        description: 'Sorting by object fields. Before field: ''+'' or nothing ->
          ASC, ''-'' -> DESC'
        required: false
        example: "-distance_to_metro,distance_to_bus,+predict_a"
        schema:
          type: string
      responses:
        '200':
          description: Successful with pagination
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/automatic_post_office_with_meta"
              examples:
                test_example:
                  value:
                    automatic_post_offices:
                    - id: 476
                      geo_data:
                      - 46589.274687
                      - 27889.421502
                      area_id: 540
                      is_placed: false
                      address: 524536 Россия, Омск, пл. Октябрьская, 845 кв. 212
                      placement_object_type_id: 490
                      people_in_range: 42735
                      distance_to_metro: 941
                      distance_to_bus: 653
                      predict_a: 13048.487
                      predict_b: 39384.378
                      predict_c: 85121.077
                    meta:
                      current_page: 1
                      next_page: 2
                      prev_page:
                      total_pages: 2
                      total_count: 2
  "/districts":
    get:
      summary: Array districts
      tags:
      - Districts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 555
                    name: площадь Заречная
                    short_name: AZ
                    square: 10.13
                    population: 888626
                    2gis_id: 9554758284
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                  - id: 556
                    name: пл. Свободы
                    short_name: GA
                    square: 51.16
                    population: 580071
                    2gis_id: 6883795555
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/district"
  "/districts/{id}":
    parameters:
    - name: id
      in: path
      description: District id
      required: true
      schema:
        type: number
    get:
      summary: Show district by id
      tags:
      - Districts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 557
                    name: улица Полевая
                    short_name: DE
                    square: 85.79
                    population: 230026
                    2gis_id: 7867859421
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                    polygon:
                    - - - 36855.330323
                        - 63675.352639
                      - - 99984.913896
                        - 64700.336089
                    polygon_type: 0
                    center_coord:
                    - 52886.757063
                    - 84550.627944
              schema:
                "$ref": "#/components/schemas/district_with_polygon"
        '404':
          description: Not found
  "/placement_object_types":
    get:
      summary: Array placement object types
      tags:
      - Automatic post offices
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 492
                    name: Legal Services
                  - id: 493
                    name: Computer Networking
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/placement_object_type"
servers:
- url: http://{defaultHost}/api/v1
  variables:
    defaultHost:
      default: 188.72.109.162:3000
