---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: This is the first version of API
components:
  schemas:
    district_with_polygon:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - polygon
      - polygon_type
      - center_coord
      - automatic_post_office_stats
    district:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - automatic_post_office_stats
    area_with_polygon:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
        emblem_url:
          type: string
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
      - polygon
      - polygon_type
      - center_coord
      - automatic_post_office_stats
    area:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        emblem_url:
          type: string
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
      - automatic_post_office_stats
    placement_object_type:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
      - id
      - name
    automatic_post_office:
      type: object
      properties:
        id:
          type: integer
        geo_data:
          type: array
          items:
            type: number
        area_id:
          type: integer
        is_placed:
          type: boolean
        address:
          type: string
        placement_object_type_id:
          type: integer
        people_in_range:
          type: integer
        distance_to_metro:
          type: integer
        distance_to_bus:
          type: integer
        predict_a:
          type: number
        predict_b:
          type: number
        predict_c:
          type: number
      required:
      - geo_data
      - area_id
      - is_placed
      - address
      - placement_object_type_id
      - people_in_range
      - distance_to_metro
      - distance_to_bus
      - predict_a
      - predict_b
      - predict_c
    meta:
      type: object
      properties:
        current_page:
          type: integer
        next_page:
          oneOf:
          - type: integer
          - type: 'null'
        prev_page:
          oneOf:
          - type: integer
          - type: 'null'
        total_pages:
          type: integer
        total_count:
          type: integer
      required:
      - current_page
      - next_page
      - prev_page
      - total_pages
      - total_count
    automatic_post_office_stats:
      type: object
      properties:
        placed:
          type: integer
        not_placed:
          type: integer
      required:
      - placed
      - not_placed
    automatic_post_office_with_meta:
      type: object
      properties:
        automatic_post_offices:
          type: array
          items:
            "$ref": "#/components/schemas/automatic_post_office"
        meta:
          "$ref": "#/components/schemas/meta"
      required:
      - automatic_post_offices
paths:
  "/areas/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: Show area by id
      tags:
      - Areas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 1474
                    population: 995859
                    square: 57526.15
                    name: Заречная ул.
                    population_density: 38.26
                    square_housing_stock: 73.08
                    living_square_per_person: 16.99
                    district_id: 1514
                    2gis_id: 1032812942
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0lGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a4953926d34cdc1d2faca35c27a88eb2544d6a1c/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                    polygon:
                    - - - 18894.008474
                        - 39656.248649
                      - - 63020.093941
                        - 26847.467783
                    polygon_type: 0
                    center_coord:
                    - 39475.898786
                    - 28925.682111
              schema:
                "$ref": "#/components/schemas/area_with_polygon"
        '404':
          description: Not found
  "/districts/{district_id}/areas":
    parameters:
    - name: district_id
      in: path
      description: District id
      required: true
      schema:
        type: integer
    get:
      summary: Array areas by district
      tags:
      - Areas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 1477
                    population: 362640
                    square: 31549.51
                    name: проспект Береговая
                    population_density: 54.13
                    square_housing_stock: 86.13
                    living_square_per_person: 90.13
                    district_id: 1517
                    2gis_id: 5650682929
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1VGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a5836acd1d53481d2de1147190c6c3053c38901b/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                  - id: 1478
                    population: 924096
                    square: 39320.67
                    name: Дзержинского площадь
                    population_density: 30.75
                    square_housing_stock: 19.31
                    living_square_per_person: 94.06
                    district_id: 1517
                    2gis_id: 4425328681
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1lGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2851e4e5e55447c389326b8850a7f903deb8783f/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/area"
  "/automatic_post_offices/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: number
    get:
      summary: Show automatic post office by id
      tags:
      - Automatic post offices
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 1314
                    geo_data:
                    - 25594.203578
                    - 35706.730514
                    area_id: 1479
                    is_placed: true
                    address: 925676 Россия, Ижевск, Трудовая ул., 318
                    placement_object_type_id: 1354
                    people_in_range: 92861
                    distance_to_metro: 590
                    distance_to_bus: 325
                    predict_a: 71700.901
                    predict_b: 97790.179
                    predict_c: 91366.324
              schema:
                "$ref": "#/components/schemas/automatic_post_office"
        '404':
          description: Not found
  "/automatic_post_offices/export_xlsx":
    post:
      summary: Export xlsx file with automatic post offices data
      tags:
      - Automatic post offices
      parameters: []
      responses:
        '404':
          description: Not found
        '200':
          description: Successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                  description: Filter by array automatic post office id's
                  example: []
                area_id:
                  type: integer
                  description: Filter by area id
                  example: 1
                district_id:
                  type: integer
                  description: Filter by district id
                  example: 7
                placement_object_type_id:
                  type: integer
                  description: Filter by placement object type id
                  example: 3
                is_placed:
                  type: boolean
                  description: Automatic post office is placed?
                sort:
                  type: string
                  description: 'Sorting by object fields. Before field: ''+'' or nothing
                    -> ASC, ''-'' -> DESC'
                  example: "-distance_to_metro,distance_to_bus,+predict_a"
        description: Filters
  "/automatic_post_offices":
    post:
      summary: Array automatic post offices with pagination
      tags:
      - Automatic post offices
      parameters: []
      responses:
        '200':
          description: Successful with pagination
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/automatic_post_office_with_meta"
              examples:
                test_example:
                  value:
                    automatic_post_offices:
                    - id: 1347
                      geo_data:
                      - 59347.567927
                      - 59463.617355
                      area_id: 1511
                      is_placed: true
                      address: 253677 Россия, Брянск, проспект Комсомольская, 344
                        кв. 257
                      placement_object_type_id: 1386
                      people_in_range: 83966
                      distance_to_metro: 799
                      distance_to_bus: 732
                      predict_a: 82047.652
                      predict_b: 18901.198
                      predict_c: 87068.096
                    meta:
                      current_page: 1
                      next_page: 2
                      prev_page:
                      total_pages: 2
                      total_count: 2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                  description: Filter by array automatic post office id's
                  example: []
                page:
                  type: integer
                  description: Page number
                  example: 1
                per_page:
                  type: integer
                  description: Number of elements per page
                  example: 1
                area_id:
                  type: integer
                  description: Filter by area id
                  example: 1
                district_id:
                  type: integer
                  description: Filter by district id
                  example: 7
                placement_object_type_id:
                  type: integer
                  description: Filter by placement object type id
                  example: 3
                is_placed:
                  type: boolean
                  description: Automatic post office is placed?
                sort:
                  type: string
                  description: 'Sorting by object fields. Before field: ''+'' or nothing
                    -> ASC, ''-'' -> DESC'
                  example: "-distance_to_metro,distance_to_bus,+predict_a"
        description: Filters
  "/districts":
    get:
      summary: Array districts
      tags:
      - Districts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 1551
                    name: Молодежная площадь
                    short_name: WA
                    square: 27.09
                    population: 585298
                    2gis_id: 9937860228
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                  - id: 1552
                    name: пр. Майская
                    short_name: WA
                    square: 99.91
                    population: 881755
                    2gis_id: 9114354949
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/district"
  "/districts/{id}":
    parameters:
    - name: id
      in: path
      description: District id
      required: true
      schema:
        type: integer
    get:
      summary: Show district by id
      tags:
      - Districts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 1553
                    name: Кооперативная проспект
                    short_name: KS
                    square: 37.87
                    population: 175043
                    2gis_id: 5817306647
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                    polygon:
                    - - - 97290.751084
                        - 51140.752349
                      - - 22163.694047
                        - 66376.635679
                    polygon_type: 1
                    center_coord:
                    - 96510.119916
                    - 61434.102765
              schema:
                "$ref": "#/components/schemas/district_with_polygon"
        '404':
          description: Not found
  "/placement_object_types":
    get:
      summary: Array placement object types
      tags:
      - Automatic post offices
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 1388
                    name: Public Policy
                  - id: 1389
                    name: Wine and Spirits
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/placement_object_type"
servers:
- url: http://{defaultHost}/api/v1
  variables:
    defaultHost:
      default: 188.72.109.162:3000
