---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: This is the first version of API
components:
  schemas:
    district_with_polygon:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - polygon
      - polygon_type
      - center_coord
      - automatic_post_office_stats
    district:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - automatic_post_office_stats
    area_with_polygon:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
        emblem_url:
          type: string
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
      - polygon
      - polygon_type
      - center_coord
      - automatic_post_office_stats
    area:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        emblem_url:
          type: string
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
      - automatic_post_office_stats
    placement_object_type:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
      - id
      - name
    automatic_post_office:
      type: object
      properties:
        id:
          type: integer
        geo_data:
          type: array
          items:
            type: number
        area_id:
          type: integer
        area_name:
          type: string
        is_placed:
          type: boolean
        address:
          type: string
        placement_object_type_id:
          type: integer
        people_in_range:
          type: integer
        distance_to_metro:
          type: integer
        distance_to_bus:
          type: integer
        predict_a:
          type: number
        predict_b:
          type: number
        predict_c:
          type: number
      required:
      - geo_data
      - area_id
      - is_placed
      - address
      - placement_object_type_id
      - people_in_range
      - distance_to_metro
      - distance_to_bus
      - predict_a
      - predict_b
      - predict_c
      - area_name
    meta:
      type: object
      properties:
        current_page:
          type: integer
        next_page:
          oneOf:
          - type: integer
          - type: 'null'
        prev_page:
          oneOf:
          - type: integer
          - type: 'null'
        total_pages:
          type: integer
        total_count:
          type: integer
      required:
      - current_page
      - next_page
      - prev_page
      - total_pages
      - total_count
    automatic_post_office_stats:
      type: object
      properties:
        placed:
          type: integer
        not_placed:
          type: integer
      required:
      - placed
      - not_placed
    automatic_post_office_with_meta:
      type: object
      properties:
        automatic_post_offices:
          type: array
          items:
            "$ref": "#/components/schemas/automatic_post_office"
        meta:
          "$ref": "#/components/schemas/meta"
      required:
      - automatic_post_offices
  securitySchemes:
    Bearer:
      description: Authorization token
      type: apiKey
      name: Authorization
      in: header
paths:
  "/areas/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: Show area by id
      tags:
      - Areas
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 2419
                    population: 406711
                    square: 68064.79
                    name: улица Майская
                    population_density: 62.02
                    square_housing_stock: 86.47
                    living_square_per_person: 21.53
                    district_id: 2481
                    2gis_id: 4860824664
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbk1KIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3523ba7d7c86e0436266ee157cd1c1f20850834e/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                    polygon:
                    - - - 61446.060079
                        - 33117.630128
                      - - 92958.249927
                        - 30628.692148
                    polygon_type: 0
                    center_coord:
                    - 22205.793024
                    - 19572.255183
              schema:
                "$ref": "#/components/schemas/area_with_polygon"
        '404':
          description: Not found
  "/districts/{district_id}/areas":
    parameters:
    - name: district_id
      in: path
      description: District id
      required: true
      schema:
        type: integer
    get:
      summary: Array areas by district
      tags:
      - Areas
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 2422
                    population: 675906
                    square: 39362.68
                    name: Труда площадь
                    population_density: 73.08
                    square_housing_stock: 87.38
                    living_square_per_person: 39.34
                    district_id: 2484
                    2gis_id: 2738094281
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbllKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--98714cac05c4595b0c56e3ac40d46601a2137b97/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                  - id: 2423
                    population: 760523
                    square: 28105.67
                    name: площадь Строителей
                    population_density: 11.73
                    square_housing_stock: 60.41
                    living_square_per_person: 39.63
                    district_id: 2484
                    2gis_id: 5234693452
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmNKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--27dfa6a8cc0f3b13699ed34cc81a82910bca2747/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/area"
  "/automatic_post_offices/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: number
    get:
      summary: Show automatic post office by id
      tags:
      - Automatic post offices
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 2171
                    geo_data:
                    - 69426.895081
                    - 73030.412111
                    area_id: 2424
                    area_name: пл. Солнечная
                    district_id: 2485
                    is_placed: true
                    address: 214873 Россия, Новокузнецк, Лесная площадь, 953 кв. 404
                    placement_object_type_id: 2257
                    people_in_range: 13937
                    distance_to_metro: 276
                    distance_to_bus: 910
                    predict_a: 72087.832
                    predict_b: 10168.998
                    predict_c: 93823.485
              schema:
                "$ref": "#/components/schemas/automatic_post_office"
        '404':
          description: Not found
  "/automatic_post_offices/export_xlsx":
    post:
      summary: Export xlsx file with automatic post offices data
      tags:
      - Automatic post offices
      parameters: []
      security:
      - Bearer: {}
      responses:
        '404':
          description: Not found
        '200':
          description: Successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                  description: Filter by array automatic post office id's
                  example: []
                area_id:
                  type: integer
                  description: Filter by area id
                  example: 1
                district_id:
                  type: integer
                  description: Filter by district id
                  example: 7
                placement_object_type_id:
                  type: integer
                  description: Filter by placement object type id
                  example: 3
                is_placed:
                  type: boolean
                  description: Automatic post office is placed?
                sort:
                  type: string
                  description: 'Sorting by object fields. Before field: ''+'' or nothing
                    -> ASC, ''-'' -> DESC'
                  example: "-distance_to_metro,distance_to_bus,+predict_a"
        description: Filters
  "/automatic_post_offices":
    post:
      summary: Array automatic post offices with pagination
      tags:
      - Automatic post offices
      parameters: []
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful with pagination
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/automatic_post_office_with_meta"
              examples:
                test_example:
                  value:
                    automatic_post_offices:
                    - id: 2204
                      geo_data:
                      - 46649.860755
                      - 24824.686703
                      area_id: 2456
                      area_name: Озерная улица
                      district_id: 2516
                      is_placed: true
                      address: 335990 Россия, Астрахань, ул. Почтовая, 468 кв. 311
                      placement_object_type_id: 2289
                      people_in_range: 55975
                      distance_to_metro: 874
                      distance_to_bus: 222
                      predict_a: 78779.461
                      predict_b: 69846.378
                      predict_c: 73981.058
                    meta:
                      current_page: 1
                      next_page: 2
                      prev_page:
                      total_pages: 2
                      total_count: 2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                  description: Filter by array automatic post office id's
                  example: []
                page:
                  type: integer
                  description: Page number
                  example: 1
                per_page:
                  type: integer
                  description: Number of elements per page
                  example: 1
                area_id:
                  type: integer
                  description: Filter by area id
                  example: 1
                district_id:
                  type: integer
                  description: Filter by district id
                  example: 7
                placement_object_type_id:
                  type: integer
                  description: Filter by placement object type id
                  example: 3
                is_placed:
                  type: boolean
                  description: Automatic post office is placed?
                sort:
                  type: string
                  description: 'Sorting by object fields. Before field: ''+'' or nothing
                    -> ASC, ''-'' -> DESC'
                  example: "-distance_to_metro,distance_to_bus,+predict_a"
        description: Filters
  "/districts":
    get:
      summary: Array districts
      tags:
      - Districts
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 2518
                    name: пр. Набережная
                    short_name: AL
                    square: 71.44
                    population: 694679
                    2gis_id: 1923069088
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                  - id: 2519
                    name: Школьная площадь
                    short_name: VT
                    square: 81.16
                    population: 507108
                    2gis_id: 4589488040
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/district"
  "/districts/{id}":
    parameters:
    - name: id
      in: path
      description: District id
      required: true
      schema:
        type: integer
    get:
      summary: Show district by id
      tags:
      - Districts
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 2520
                    name: площадь Суворова
                    short_name: NJ
                    square: 70.37
                    population: 791387
                    2gis_id: 6430837255
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                    polygon:
                    - - - 16306.515689
                        - 86693.477541
                      - - 70812.981914
                        - 91075.946001
                    polygon_type: 1
                    center_coord:
                    - 92889.982564
                    - 90774.069912
              schema:
                "$ref": "#/components/schemas/district_with_polygon"
        '404':
          description: Not found
  "/placement_object_types":
    get:
      summary: Array placement object types
      tags:
      - Automatic post offices
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 2291
                    name: Pharmaceuticals
                  - id: 2292
                    name: Food & Beverages
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/placement_object_type"
  "/users/login":
    post:
      summary: Authenticate user
      tags:
      - Authenticate
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    auth_token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Njg0NTg2MzgsImlzcyI6Imlzc3Vlcl9uYW1lIiwiYXVkIjoiY2xpZW50IiwidXNlcl9pZCI6MTI3M30.SC_Qs28iTQmXPKQ8gf70jRHYsEJJ24k7B3W_6cc6Ylg
              schema:
                auth_token:
                  type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                test_example:
                  value:
                    error: Invalid username / password
              schema:
                error:
                  type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
servers:
- url: http://{defaultHost}/api/v1
  variables:
    defaultHost:
      default: 188.72.109.162:3000
