---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: This is the first version of API
components:
  schemas:
    district_with_polygon:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - polygon
      - polygon_type
      - center_coord
      - automatic_post_office_stats
    district:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - automatic_post_office_stats
    area_with_polygon:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
        emblem_url:
          type: string
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
      - polygon
      - polygon_type
      - center_coord
      - automatic_post_office_stats
    area:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        emblem_url:
          type: string
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
      - automatic_post_office_stats
    placement_object_type:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
      - id
      - name
    automatic_post_office:
      type: object
      properties:
        id:
          type: integer
        geo_data:
          type: array
          items:
            type: number
        area_id:
          type: integer
        area_name:
          type: string
        is_placed:
          type: boolean
        address:
          type: string
        placement_object_type_id:
          type: integer
        people_in_range:
          type: integer
        distance_to_metro:
          type: integer
        distance_to_bus:
          type: integer
        predict_a:
          type: number
        predict_b:
          type: number
        predict_c:
          type: number
      required:
      - geo_data
      - area_id
      - is_placed
      - address
      - placement_object_type_id
      - people_in_range
      - distance_to_metro
      - distance_to_bus
      - predict_a
      - predict_b
      - predict_c
      - area_name
    meta:
      type: object
      properties:
        current_page:
          type: integer
        next_page:
          oneOf:
          - type: integer
          - type: 'null'
        prev_page:
          oneOf:
          - type: integer
          - type: 'null'
        total_pages:
          type: integer
        total_count:
          type: integer
      required:
      - current_page
      - next_page
      - prev_page
      - total_pages
      - total_count
    automatic_post_office_stats:
      type: object
      properties:
        placed:
          type: integer
        not_placed:
          type: integer
      required:
      - placed
      - not_placed
    automatic_post_office_with_meta:
      type: object
      properties:
        automatic_post_offices:
          type: array
          items:
            "$ref": "#/components/schemas/automatic_post_office"
        meta:
          "$ref": "#/components/schemas/meta"
      required:
      - automatic_post_offices
  securitySchemes:
    Bearer:
      description: Authorization token
      type: apiKey
      name: Authorization
      in: header
paths:
  "/areas/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: Show area by id
      tags:
      - Areas
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 2497
                    population: 715970
                    square: 67000.88
                    name: Почтовая улица
                    population_density: 82.34
                    square_housing_stock: 70.97
                    living_square_per_person: 51.88
                    district_id: 2561
                    2gis_id: 1567683590
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0VKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5dd9b14823f2ca03c0881ee0cceb006c17c7f4b3/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                    polygon:
                    - - - 39139.535006
                        - 26668.732183
                      - - 36922.431964
                        - 12760.640452
                    polygon_type: 1
                    center_coord:
                    - 23014.148952
                    - 50364.706802
              schema:
                "$ref": "#/components/schemas/area_with_polygon"
        '404':
          description: Not found
  "/districts/{district_id}/areas":
    parameters:
    - name: district_id
      in: path
      description: District id
      required: true
      schema:
        type: integer
    get:
      summary: Array areas by district
      tags:
      - Areas
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 2500
                    population: 253734
                    square: 46153.15
                    name: Гоголя улица
                    population_density: 67.07
                    square_housing_stock: 43.38
                    living_square_per_person: 76.99
                    district_id: 2564
                    2gis_id: 6639352779
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1FKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d7fbf56fba818830ae8ea8494991c73ee31e53ab/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                  - id: 2501
                    population: 338769
                    square: 15863.85
                    name: Спортивная площадь
                    population_density: 96.52
                    square_housing_stock: 50.98
                    living_square_per_person: 15.74
                    district_id: 2564
                    2gis_id: 8466899978
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc1VKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--66bdfb1c0c3c31f03cb53fb8ba85ab85f5372730/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/area"
  "/automatic_post_offices/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: number
    get:
      summary: Show automatic post office by id
      tags:
      - Automatic post offices
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 2241
                    geo_data:
                    - 42851.519732
                    - 65796.886856
                    area_id: 2502
                    area_name: Советская ул.
                    district_id: 2565
                    is_placed: false
                    address: 805630 Россия, Новокузнецк, ул. Рабочая, 948 кв. 311
                    placement_object_type_id: 2329
                    people_in_range: 86358
                    distance_to_metro: 363
                    distance_to_bus: 785
                    predict_a: 22756.352
                    predict_b: 28363.372
                    predict_c: 15231.029
              schema:
                "$ref": "#/components/schemas/automatic_post_office"
        '404':
          description: Not found
  "/automatic_post_offices/export_xlsx":
    post:
      summary: Export xlsx file with automatic post offices data
      tags:
      - Automatic post offices
      parameters: []
      security:
      - Bearer: {}
      responses:
        '404':
          description: Not found
        '200':
          description: Successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                  description: Filter by array automatic post office id's
                  example: []
                area_id:
                  type: integer
                  description: Filter by area id
                  example: 1
                district_id:
                  type: integer
                  description: Filter by district id
                  example: 7
                placement_object_type_id:
                  type: integer
                  description: Filter by placement object type id
                  example: 3
                is_placed:
                  type: boolean
                  description: Automatic post office is placed?
                sort:
                  type: string
                  description: 'Sorting by object fields. Before field: ''+'' or nothing
                    -> ASC, ''-'' -> DESC'
                  example: "-distance_to_metro,distance_to_bus,+predict_a"
        description: Filters
  "/automatic_post_offices":
    post:
      summary: Array automatic post offices with pagination
      tags:
      - Automatic post offices
      parameters: []
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful with pagination
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/automatic_post_office_with_meta"
              examples:
                test_example:
                  value:
                    automatic_post_offices:
                    - id: 2274
                      geo_data:
                      - 11336.963962
                      - 38808.039931
                      area_id: 2534
                      area_name: Калинина ул.
                      district_id: 2596
                      is_placed: false
                      address: 452689 Россия, Пермь, Солнечная улица, 609 кв. 230
                      placement_object_type_id: 2361
                      people_in_range: 96199
                      distance_to_metro: 845
                      distance_to_bus: 237
                      predict_a: 19021.148
                      predict_b: 34876.104
                      predict_c: 69748.948
                    meta:
                      current_page: 1
                      next_page: 2
                      prev_page:
                      total_pages: 2
                      total_count: 2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                  description: Filter by array automatic post office id's
                  example: []
                page:
                  type: integer
                  description: Page number
                  example: 1
                per_page:
                  type: integer
                  description: Number of elements per page
                  example: 1
                area_id:
                  type: integer
                  description: Filter by area id
                  example: 1
                district_id:
                  type: integer
                  description: Filter by district id
                  example: 7
                placement_object_type_id:
                  type: integer
                  description: Filter by placement object type id
                  example: 3
                is_placed:
                  type: boolean
                  description: Automatic post office is placed?
                sort:
                  type: string
                  description: 'Sorting by object fields. Before field: ''+'' or nothing
                    -> ASC, ''-'' -> DESC'
                  example: "-distance_to_metro,distance_to_bus,+predict_a"
        description: Filters
  "/districts":
    get:
      summary: Array districts
      tags:
      - Districts
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 2598
                    name: пр. Речная
                    short_name: MA
                    square: 66.74
                    population: 507130
                    2gis_id: 4336348234
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                  - id: 2599
                    name: проспект Солнечная
                    short_name: MA
                    square: 28.16
                    population: 356473
                    2gis_id: 2892357673
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/district"
  "/districts/{id}":
    parameters:
    - name: id
      in: path
      description: District id
      required: true
      schema:
        type: integer
    get:
      summary: Show district by id
      tags:
      - Districts
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 2600
                    name: улица Садовая
                    short_name: GA
                    square: 92.43
                    population: 706358
                    2gis_id: 3351918352
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                    polygon:
                    - - - 60662.475566
                        - 63747.813156
                      - - 38999.052882
                        - 82294.208793
                    polygon_type: 1
                    center_coord:
                    - 10707.225082
                    - 95454.730703
              schema:
                "$ref": "#/components/schemas/district_with_polygon"
        '404':
          description: Not found
  "/placement_object_types":
    get:
      summary: Array placement object types
      tags:
      - Automatic post offices
      security:
      - Bearer: {}
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 2363
                    name: Business Supplies and Equipment
                  - id: 2364
                    name: Marketing and Advertising
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/placement_object_type"
  "/users/login":
    post:
      summary: Authenticate user
      tags:
      - Authenticate
      parameters: []
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    auth_token: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Njg0NTk3OTgsImlzcyI6Imlzc3Vlcl9uYW1lIiwiYXVkIjoiY2xpZW50IiwidXNlcl9pZCI6MTMxN30.VKZR9dmPbEd0OVacPbLW6ssm1KPHX0Fy1XRrJK_A-DM
              schema:
                auth_token:
                  type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                test_example:
                  value:
                    error: Invalid username / password
              schema:
                error:
                  type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
servers:
- url: http://{defaultHost}/api/v1
  variables:
    defaultHost:
      default: 188.72.109.162:3000
