---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: This is the first version of API
components:
  schemas:
    district_with_polygon:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - polygon
      - polygon_type
      - center_coord
      - automatic_post_office_stats
    district:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - automatic_post_office_stats
    area_with_polygon:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
        emblem_url:
          type: string
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
      - polygon
      - polygon_type
      - center_coord
      - automatic_post_office_stats
    area:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        emblem_url:
          type: string
        automatic_post_office_stats:
          "$ref": "#/components/schemas/automatic_post_office_stats"
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - emblem_url
      - automatic_post_office_stats
    placement_object_type:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
      - id
      - name
    automatic_post_office:
      type: object
      properties:
        id:
          type: integer
        geo_data:
          type: array
          items:
            type: number
        area_id:
          type: integer
        area_name:
          type: string
        is_placed:
          type: boolean
        address:
          type: string
        placement_object_type_id:
          type: integer
        people_in_range:
          type: integer
        distance_to_metro:
          type: integer
        distance_to_bus:
          type: integer
        predict_a:
          type: number
        predict_b:
          type: number
        predict_c:
          type: number
      required:
      - geo_data
      - area_id
      - is_placed
      - address
      - placement_object_type_id
      - people_in_range
      - distance_to_metro
      - distance_to_bus
      - predict_a
      - predict_b
      - predict_c
      - area_name
    meta:
      type: object
      properties:
        current_page:
          type: integer
        next_page:
          oneOf:
          - type: integer
          - type: 'null'
        prev_page:
          oneOf:
          - type: integer
          - type: 'null'
        total_pages:
          type: integer
        total_count:
          type: integer
      required:
      - current_page
      - next_page
      - prev_page
      - total_pages
      - total_count
    automatic_post_office_stats:
      type: object
      properties:
        placed:
          type: integer
        not_placed:
          type: integer
      required:
      - placed
      - not_placed
    automatic_post_office_with_meta:
      type: object
      properties:
        automatic_post_offices:
          type: array
          items:
            "$ref": "#/components/schemas/automatic_post_office"
        meta:
          "$ref": "#/components/schemas/meta"
      required:
      - automatic_post_offices
paths:
  "/areas/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: integer
    get:
      summary: Show area by id
      tags:
      - Areas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 1591
                    population: 316801
                    square: 62141.34
                    name: Парковая ул.
                    population_density: 69.75
                    square_housing_stock: 65.75
                    living_square_per_person: 54.05
                    district_id: 1634
                    2gis_id: 6984365844
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBamNHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6390254958ec8e351d2e776d569ac776b48f344b/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                    polygon:
                    - - - 53658.170438
                        - 17697.389011
                      - - 10726.502878
                        - 51630.315464
                    polygon_type: 1
                    center_coord:
                    - 36063.446158
                    - 27985.851449
              schema:
                "$ref": "#/components/schemas/area_with_polygon"
        '404':
          description: Not found
  "/districts/{district_id}/areas":
    parameters:
    - name: district_id
      in: path
      description: District id
      required: true
      schema:
        type: integer
    get:
      summary: Array areas by district
      tags:
      - Areas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 1594
                    population: 119836
                    square: 75720.57
                    name: площадь Цветочная
                    population_density: 13.99
                    square_housing_stock: 41.65
                    living_square_per_person: 75.02
                    district_id: 1637
                    2gis_id: 1890605279
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBam9HIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5d157714ebe9a066742cc6849834af8d1423195a/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                  - id: 1595
                    population: 236591
                    square: 67535.11
                    name: пл. Весенняя
                    population_density: 67.89
                    square_housing_stock: 46.47
                    living_square_per_person: 66.07
                    district_id: 1637
                    2gis_id: 8618619808
                    emblem_url: http://localhost:3000/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanNHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b051ceba126e534db5624d815ac95a6962c8f6d8/emblem.png
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/area"
  "/automatic_post_offices/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: number
    get:
      summary: Show automatic post office by id
      tags:
      - Automatic post offices
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 1419
                    geo_data:
                    - 76573.689742
                    - 40357.823435
                    area_id: 1596
                    area_name: Крупской ул.
                    is_placed: true
                    address: 124517 Россия, Чебоксары, пр. Весенняя, 392 кв. 884
                    placement_object_type_id: 1462
                    people_in_range: 63388
                    distance_to_metro: 245
                    distance_to_bus: 588
                    predict_a: 72322.805
                    predict_b: 32471.632
                    predict_c: 51458.246
              schema:
                "$ref": "#/components/schemas/automatic_post_office"
        '404':
          description: Not found
  "/automatic_post_offices/export_xlsx":
    post:
      summary: Export xlsx file with automatic post offices data
      tags:
      - Automatic post offices
      parameters: []
      responses:
        '404':
          description: Not found
        '200':
          description: Successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                  description: Filter by array automatic post office id's
                  example: []
                area_id:
                  type: integer
                  description: Filter by area id
                  example: 1
                district_id:
                  type: integer
                  description: Filter by district id
                  example: 7
                placement_object_type_id:
                  type: integer
                  description: Filter by placement object type id
                  example: 3
                is_placed:
                  type: boolean
                  description: Automatic post office is placed?
                sort:
                  type: string
                  description: 'Sorting by object fields. Before field: ''+'' or nothing
                    -> ASC, ''-'' -> DESC'
                  example: "-distance_to_metro,distance_to_bus,+predict_a"
        description: Filters
  "/automatic_post_offices":
    post:
      summary: Array automatic post offices with pagination
      tags:
      - Automatic post offices
      parameters: []
      responses:
        '200':
          description: Successful with pagination
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/automatic_post_office_with_meta"
              examples:
                test_example:
                  value:
                    automatic_post_offices:
                    - id: 1452
                      geo_data:
                      - 97110.654104
                      - 39036.009571
                      area_id: 1628
                      area_name: площадь Центральная
                      is_placed: true
                      address: 389942 Россия, Кемерово, Вокзальная пр., 252
                      placement_object_type_id: 1494
                      people_in_range: 25533
                      distance_to_metro: 456
                      distance_to_bus: 146
                      predict_a: 64201.511
                      predict_b: 83422.005
                      predict_c: 84291.275
                    meta:
                      current_page: 1
                      next_page: 2
                      prev_page:
                      total_pages: 2
                      total_count: 2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                  description: Filter by array automatic post office id's
                  example: []
                page:
                  type: integer
                  description: Page number
                  example: 1
                per_page:
                  type: integer
                  description: Number of elements per page
                  example: 1
                area_id:
                  type: integer
                  description: Filter by area id
                  example: 1
                district_id:
                  type: integer
                  description: Filter by district id
                  example: 7
                placement_object_type_id:
                  type: integer
                  description: Filter by placement object type id
                  example: 3
                is_placed:
                  type: boolean
                  description: Automatic post office is placed?
                sort:
                  type: string
                  description: 'Sorting by object fields. Before field: ''+'' or nothing
                    -> ASC, ''-'' -> DESC'
                  example: "-distance_to_metro,distance_to_bus,+predict_a"
        description: Filters
  "/districts":
    get:
      summary: Array districts
      tags:
      - Districts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 1671
                    name: проспект Южная
                    short_name: TN
                    square: 98.13
                    population: 631982
                    2gis_id: 5656772221
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                  - id: 1672
                    name: Южная пр.
                    short_name: NE
                    square: 72.79
                    population: 111885
                    2gis_id: 9736382884
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/district"
  "/districts/{id}":
    parameters:
    - name: id
      in: path
      description: District id
      required: true
      schema:
        type: integer
    get:
      summary: Show district by id
      tags:
      - Districts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 1673
                    name: Маяковского ул.
                    short_name: ME
                    square: 58.26
                    population: 309472
                    2gis_id: 6419321509
                    automatic_post_office_stats:
                      placed: 0
                      not_placed: 0
                    polygon:
                    - - - 50803.528355
                        - 35455.906414
                      - - 39433.486236
                        - 75019.228879
                    polygon_type: 1
                    center_coord:
                    - 60502.109179
                    - 98969.693529
              schema:
                "$ref": "#/components/schemas/district_with_polygon"
        '404':
          description: Not found
  "/placement_object_types":
    get:
      summary: Array placement object types
      tags:
      - Automatic post offices
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 1496
                    name: Sporting Goods
                  - id: 1497
                    name: Cosmetics
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/placement_object_type"
servers:
- url: http://{defaultHost}/api/v1
  variables:
    defaultHost:
      default: 188.72.109.162:3000
