---
openapi: 3.0.1
info:
  title: API V1
  version: v1
  description: This is the first version of API
components:
  schemas:
    district_with_polygon:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
      - polygon
      - polygon_type
      - center_coord
    district:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        short_name:
          type: string
        square:
          type: number
        population:
          type: integer
        2gis_id:
          type: integer
      required:
      - id
      - name
      - short_name
      - square
      - population
      - 2gis_id
    area_with_polygon:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
        polygon:
          type: array
          items:
            type: array
            items:
              type: array
              items:
                type: number
        polygon_type:
          type: integer
        center_coord:
          type: array
          items:
            type: number
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
      - polygon
      - polygon_type
      - center_coord
    area:
      type: object
      properties:
        id:
          type: integer
        population:
          type: integer
        name:
          type: string
        square:
          type: number
        population_density:
          type: number
        square_housing_stock:
          type: number
        living_square_per_person:
          type: number
        district_id:
          type: integer
        2gis_id:
          type: integer
      required:
      - id
      - population
      - square
      - name
      - population_density
      - square_housing_stock
      - living_square_per_person
      - district_id
      - 2gis_id
paths:
  "/areas/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Show area by id
      tags:
      - Areas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 36
                    population: 953668
                    square: 62659.93
                    name: Guillermo Islands
                    population_density: 78.82
                    square_housing_stock: 41.55
                    living_square_per_person: 27.79
                    district_id: 44
                    2gis_id: 7431719650
                    polygon:
                    - - - 98733.828539
                        - 15441.773766
                      - - 15985.605221
                        - 85575.505393
                    polygon_type: 0
                    center_coord:
                    - 59948.674288
                    - 96385.572875
              schema:
                "$ref": "#/components/schemas/area_with_polygon"
        '404':
          description: Not found
  "/districts/{district_id}/areas":
    parameters:
    - name: district_id
      in: path
      description: district_id
      required: true
      schema:
        type: string
    get:
      summary: Array areas by district
      tags:
      - Areas
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 39
                    population: 119909
                    square: 51788.65
                    name: Bette Mission
                    population_density: 88.66
                    square_housing_stock: 70.72
                    living_square_per_person: 16.11
                    district_id: 47
                    2gis_id: 9278207423
                  - id: 40
                    population: 963356
                    square: 64455.44
                    name: Rowe Key
                    population_density: 94.86
                    square_housing_stock: 90.61
                    living_square_per_person: 85.17
                    district_id: 47
                    2gis_id: 5235868138
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/area"
  "/districts":
    get:
      summary: Array districts
      tags:
      - Districts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                  - id: 48
                    name: Reinger Throughway
                    short_name: OK
                    square: 84.62
                    population: 317204
                    2gis_id: 9165034846
                  - id: 49
                    name: Neal Stravenue
                    short_name: NJ
                    square: 92.42
                    population: 711359
                    2gis_id: 3404533862
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/district"
  "/districts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: Show district by id
      tags:
      - Districts
      responses:
        '200':
          description: Successful
          content:
            application/json:
              examples:
                test_example:
                  value:
                    id: 50
                    name: Sawayn Prairie
                    short_name: PA
                    square: 94.59
                    population: 603761
                    2gis_id: 2301859815
                    polygon:
                    - - - 41533.058587
                        - 63902.835575
                      - - 91352.659461
                        - 12636.383697
                    polygon_type: 1
                    center_coord:
                    - 30418.165018
                    - 93607.706632
              schema:
                "$ref": "#/components/schemas/district_with_polygon"
        '404':
          description: Not found
servers:
- url: http://{defaultHost}/api/v1
  variables:
    defaultHost:
      default: 188.72.109.162:3000
